// Traducción de rubros para mostrar en la UI. El valor que se guarda en
// `negocios.rubro` es la categoría cruda tal como la devuelve la fuente
// (categories.primary de Overture, antes tags de OSM) — eso NO se toca,
// sigue siendo la clave interna para filtrar/agrupar. Esto es solo la capa
// de traducción para mostrárselo al usuario en español. La taxonomía de
// Overture tiene miles de categorías puntuales (ver
// github.com/OvertureMaps/schema): solo mapeamos las más comunes vistas en
// uso real, el resto cae en el fallback formateado en inglés.
const TRADUCCIONES: Record<string, string> = {
  // amenity=*
  restaurant: 'Restaurante',
  cafe: 'Café',
  fast_food: 'Comida rápida',
  bar: 'Bar',
  pub: 'Pub',
  ice_cream: 'Heladería',
  bank: 'Banco',
  pharmacy: 'Farmacia',
  doctors: 'Médicos',
  dentist: 'Dentista',
  clinic: 'Clínica',
  hospital: 'Hospital',
  veterinary: 'Veterinaria',
  place_of_worship: 'Lugar de culto',
  school: 'Escuela',
  university: 'Universidad',
  college: 'Instituto terciario',
  kindergarten: 'Jardín de infantes',
  library: 'Biblioteca',
  post_office: 'Correo',
  police: 'Policía',
  fuel: 'Estación de servicio',
  car_wash: 'Lavadero de autos',
  car_rental: 'Alquiler de autos',
  cinema: 'Cine',
  theatre: 'Teatro',
  nightclub: 'Boliche',
  gym: 'Gimnasio',
  fitness_centre: 'Gimnasio',
  coworking_space: 'Coworking',
  events_venue: 'Salón de eventos',
  community_centre: 'Centro comunitario',
  courthouse: 'Tribunal',
  townhall: 'Municipalidad',
  embassy: 'Embajada',
  driving_school: 'Autoescuela',
  language_school: 'Instituto de idiomas',
  music_school: 'Escuela de música',
  childcare: 'Guardería',
  social_facility: 'Centro social',
  casino: 'Casino',
  marketplace: 'Mercado',
  bicycle_rental: 'Alquiler de bicicletas',
  parking: 'Estacionamiento',
  kiosk: 'Kiosco',
  clothing_store: 'Tienda de ropa',

  // shop=*
  supermarket: 'Supermercado',
  convenience: 'Almacén / Kiosco',
  bakery: 'Panadería',
  butcher: 'Carnicería',
  greengrocer: 'Verdulería',
  clothes: 'Ropa',
  shoes: 'Zapatería',
  hairdresser: 'Peluquería',
  beauty: 'Centro de estética',
  electronics: 'Electrónica',
  mobile_phone: 'Celulares',
  furniture: 'Muebles',
  hardware: 'Ferretería',
  doityourself: 'Ferretería / Bricolaje',
  books: 'Librería',
  stationery: 'Papelería',
  jewelry: 'Joyería',
  optician: 'Óptica',
  pet: 'Petshop',
  toys: 'Juguetería',
  sports: 'Artículos deportivos',
  car: 'Concesionaria de autos',
  car_repair: 'Taller mecánico',
  car_parts: 'Repuestos de autos',
  bicycle: 'Bicicletería',
  travel_agency: 'Agencia de viajes',
  laundry: 'Lavandería',
  dry_cleaning: 'Tintorería',
  florist: 'Florería',
  gift: 'Regalería',
  variety_store: 'Bazar',
  department_store: 'Tienda por departamentos',
  mall: 'Shopping',
  alcohol: 'Vinoteca',
  wine: 'Vinoteca',
  confectionery: 'Confitería',
  chocolate: 'Chocolatería',
  deli: 'Fiambrería',
  seafood: 'Pescadería',
  tobacco: 'Kiosco de tabaco',
  newsagent: 'Kiosco de diarios',
  copyshop: 'Fotocopiadora',
  computer: 'Informática',
  photo: 'Fotografía',
  tailor: 'Sastrería',
  locksmith: 'Cerrajería',
  paint: 'Pinturería',
  garden_centre: 'Vivero',
  chemist: 'Farmacia',
  real_estate_agent: 'Inmobiliaria',
  insurance: 'Seguros',
  lottery: 'Agencia de quiniela',

  // office=*
  company: 'Empresa',
  lawyer: 'Estudio jurídico',
  accountant: 'Contador',
  estate_agent: 'Inmobiliaria',
  financial: 'Servicios financieros',
  financial_advisor: 'Asesor financiero',
  diplomatic: 'Oficina diplomática',
  government: 'Oficina gubernamental',
  it: 'Tecnología / IT',
  architect: 'Estudio de arquitectura',
  engineer: 'Ingeniería',
  consulting: 'Consultora',
  advertising_agency: 'Agencia de publicidad',
  educational_institution: 'Institución educativa',
  employment_agency: 'Agencia de empleo',
  coworking: 'Coworking',
  association: 'Asociación',
  ngo: 'ONG',
  notary: 'Escribanía',
  tax_advisor: 'Asesor impositivo',
  travel_agent: 'Agencia de viajes',

  // craft=*
  electrician: 'Electricista',
  plumber: 'Plomero',
  carpenter: 'Carpintero',
  painter: 'Pintor',
  photographer: 'Fotógrafo',
  shoemaker: 'Zapatero remendón',
  hvac: 'Climatización',
  metal_construction: 'Herrería',
  upholsterer: 'Tapicero',
  gardener: 'Jardinero',

  // categories.primary de Overture (taxonomía propia, no siempre coincide
  // con los tags de OSM de arriba)
  italian_restaurant: 'Restaurante italiano',
  pizza_restaurant: 'Pizzería',
  mexican_restaurant: 'Restaurante mexicano',
  chinese_restaurant: 'Restaurante chino',
  japanese_restaurant: 'Restaurante japonés',
  seafood_restaurant: 'Marisquería',
  steakhouse: 'Parrilla',
  vegetarian_restaurant: 'Restaurante vegetariano',
  breakfast_brunch_restaurant: 'Desayunos y brunch',
  bakery_and_pastry_shop: 'Panadería',
  ice_cream_shop: 'Heladería',
  coffee_shop: 'Café',
  brewery: 'Cervecería',
  wine_bar: 'Vinoteca / Wine bar',
  cocktail_bar: 'Coctelería',
  dance_club: 'Boliche',
  convenience_store: 'Almacén / Kiosco',
  grocery_store: 'Almacén',
  shoe_store: 'Zapatería',
  fashion: 'Tienda de ropa',
  hair_salon: 'Peluquería',
  nail_salon: 'Salón de uñas',
  spa: 'Spa',
  gym_and_fitness_center: 'Gimnasio',
  hotel: 'Hotel',
  auto_repair: 'Taller mecánico',
  gas_station: 'Estación de servicio',
  professional_services: 'Servicios profesionales',
  architectural_designer: 'Estudio de arquitectura',
  money_transfer_services: 'Envío de dinero',
  insurance_agency: 'Seguros',
  central_government_office: 'Oficina gubernamental',
  local_government_office: 'Oficina gubernamental',
  medical_clinic: 'Clínica',
  veterinarian: 'Veterinaria',
};

// Fallback para tags sin traducción cargada: "fast_food" -> "Fast food"
// (también es lo que se usa siempre en inglés: el tag de OSM ya es inglés,
// solo hace falta formatearlo prolijo).
function formatearFallback(rubro: string): string {
  return rubro
    .split('_')
    .map((palabra) => palabra.charAt(0).toUpperCase() + palabra.slice(1))
    .join(' ');
}

export function traducirRubro(rubro: string | null | undefined, lang: 'es' | 'en' = 'es'): string {
  if (!rubro) return '';
  if (lang === 'en') return formatearFallback(rubro);
  return TRADUCCIONES[rubro] ?? formatearFallback(rubro);
}
